// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/harcama.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5291797905697239567),
      name: 'Harcama',
      lastPropertyId: const obx_int.IdUid(7, 387774212397392735),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1851255042722301758),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2472601368384972959),
            name: 'kategori',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3417403459507138343),
            name: 'aciklama',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3061238153020581723),
            name: 'tutar',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 191334576088325764),
            name: 'tarih',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 387774212397392735),
            name: 'ikonAdi',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5291797905697239567),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [6995894177672892932],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Harcama: obx_int.EntityDefinition<Harcama>(
        model: _entities[0],
        toOneRelations: (Harcama object) => [],
        toManyRelations: (Harcama object) => {},
        getId: (Harcama object) => object.id,
        setId: (Harcama object, int id) {
          object.id = id;
        },
        objectToFB: (Harcama object, fb.Builder fbb) {
          final kategoriOffset = fbb.writeString(object.kategori);
          final aciklamaOffset = fbb.writeString(object.aciklama);
          final ikonAdiOffset = fbb.writeString(object.ikonAdi);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, kategoriOffset);
          fbb.addOffset(2, aciklamaOffset);
          fbb.addFloat64(3, object.tutar);
          fbb.addInt64(5, object.tarih.millisecondsSinceEpoch);
          fbb.addOffset(6, ikonAdiOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final kategoriParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final aciklamaParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final tutarParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final ikonAdiParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final tarihParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = Harcama(
              id: idParam,
              kategori: kategoriParam,
              aciklama: aciklamaParam,
              tutar: tutarParam,
              ikonAdi: ikonAdiParam,
              tarih: tarihParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Harcama] entity fields to define ObjectBox queries.
class Harcama_ {
  /// see [Harcama.id]
  static final id =
      obx.QueryIntegerProperty<Harcama>(_entities[0].properties[0]);

  /// see [Harcama.kategori]
  static final kategori =
      obx.QueryStringProperty<Harcama>(_entities[0].properties[1]);

  /// see [Harcama.aciklama]
  static final aciklama =
      obx.QueryStringProperty<Harcama>(_entities[0].properties[2]);

  /// see [Harcama.tutar]
  static final tutar =
      obx.QueryDoubleProperty<Harcama>(_entities[0].properties[3]);

  /// see [Harcama.tarih]
  static final tarih =
      obx.QueryDateProperty<Harcama>(_entities[0].properties[4]);

  /// see [Harcama.ikonAdi]
  static final ikonAdi =
      obx.QueryStringProperty<Harcama>(_entities[0].properties[5]);
}
